<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <!-- id parent -->
    <groupId>com.crdev</groupId>
    <artifactId>msvc-reactive-web-flux</artifactId>
    <version>1.0-SNAPSHOT</version>

    <!-- lookup parent from repository -->
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>4.1.1</version>
        <relativePath/>
    </parent>

    <modules>
        <module>1_msvc_crud_products</module>
        <module>2_msvc_names_reactive</module>
        <module>2b-msvc_names_reactive_funcional</module>
        <module>3_msvc_crud_productos_reactivo</module>
        <module>3b_msvc_crud_productos_reactivo_2</module>
        <module>5_test-crud-products-spring</module>
        <module>6_msvc_rastrear</module>
        <module>8_msvc_crud_productos_reactivo-securizado</module>
        <module>8a-msvc_crud_productos_reactivo-securizado-jwt-db</module>
        <module>8b-msvc_crud_productos_reactivo-securizado-jwt</module>
        <module>9_msvc_rastrear</module>
        <module>9b-msvc_rastrear-jwt</module>
        <module>10-msvc_crud_productos_reactivo-bd</module>
        <module>10b-msvc_crud_productos_reactivo-bd-funtional-endpoint</module>
        <module>11_app_example_consumer</module>
        <module>12_app_example_producer</module>
        <module>13_msvc_orders</module>
        <module>14_msvc_crud_productos_reactivo-bd-funtional-endpoint</module>
        <module>15_msvc_envios</module>
        <module>16_svc_eureka</module>
        <module>17_msvc_crud_productos_reactivo_tienda_1_eureka</module>
        <module>18_msvc_crud_productos_reactivo_tienda_2_eureka</module>
        <module>19_msvc_rastrear_eureka</module>
        <module>20_svc_gateway</module>
    </modules>


    <properties>
        <java.version>26</java.version>
        <maven.compiler.source>26</maven.compiler.source>
        <maven.compiler.target>26</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <packaging>pom</packaging>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <excludes>
                        <exclude>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                        </exclude>
                    </excludes>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <executions>
                    <execution>
                        <id>default-compile</id>
                        <phase>compile</phase>
                        <goals>
                            <goal>compile</goal>
                        </goals>
                        <configuration>
                            <annotationProcessorPaths>
                                <path>
                                    <groupId>org.projectlombok</groupId>
                                    <artifactId>lombok</artifactId>
                                </path>
                            </annotationProcessorPaths>
                        </configuration>
                    </execution>
                    <execution>
                        <id>default-testCompile</id>
                        <phase>test-compile</phase>
                        <goals>
                            <goal>testCompile</goal>
                        </goals>
                        <configuration>
                            <annotationProcessorPaths>
                                <path>
                                    <groupId>org.projectlombok</groupId>
                                    <artifactId>lombok</artifactId>
                                </path>
                            </annotationProcessorPaths>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>