server:
  port: 8761
spring:
  application:
    name: svc_eureka

# propiedad para que el propio servidor de eureka no se registre en si mismo
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
